# Generated by Django 4.2.5 on 2023-09-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reporter',
            new_name='lesson',
        ),
    ]
