# Generated by Django 4.2.5 on 2023-09-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_reporter_product_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='access_user',
            new_name='access_product',
        ),
    ]
