# Generated by Django 4.2.5 on 2023-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_lessonstatus_time_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstatus',
            name='view_status',
            field=models.BooleanField(auto_created=True, default=False, editable=False),
        ),
    ]
