# Generated by Django 4.2.5 on 2023-09-21 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lessonstatus_view_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstatus',
            name='view_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
